//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImrPlatform.JirehService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JirehService.IJirehFramework")]
    public interface IJirehFramework {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/CallService", ReplyAction="http://tempuri.org/IJirehFramework/CallServiceResponse")]
        string CallService(string sInputMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/CallService", ReplyAction="http://tempuri.org/IJirehFramework/CallServiceResponse")]
        System.Threading.Tasks.Task<string> CallServiceAsync(string sInputMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IJirehFramework/GetDataUsingDataContractResponse")]
        ImrPlatform.JirehService.CompositeType GetDataUsingDataContract(ImrPlatform.JirehService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IJirehFramework/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ImrPlatform.JirehService.CompositeType> GetDataUsingDataContractAsync(ImrPlatform.JirehService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/FileDownload", ReplyAction="http://tempuri.org/IJirehFramework/FileDownloadResponse")]
        string FileDownload(string sDownloadUri, string sPort, string sUserID, string sUserPassword, string sFilename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/FileDownload", ReplyAction="http://tempuri.org/IJirehFramework/FileDownloadResponse")]
        System.Threading.Tasks.Task<string> FileDownloadAsync(string sDownloadUri, string sPort, string sUserID, string sUserPassword, string sFilename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/HttpDownload", ReplyAction="http://tempuri.org/IJirehFramework/HttpDownloadResponse")]
        string HttpDownload(string FileKind, string FilePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJirehFramework/HttpDownload", ReplyAction="http://tempuri.org/IJirehFramework/HttpDownloadResponse")]
        System.Threading.Tasks.Task<string> HttpDownloadAsync(string FileKind, string FilePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJirehFrameworkChannel : ImrPlatform.JirehService.IJirehFramework, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JirehFrameworkClient : System.ServiceModel.ClientBase<ImrPlatform.JirehService.IJirehFramework>, ImrPlatform.JirehService.IJirehFramework {
        
        public JirehFrameworkClient() {
        }
        
        public JirehFrameworkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JirehFrameworkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JirehFrameworkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JirehFrameworkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CallService(string sInputMessage) {
            return base.Channel.CallService(sInputMessage);
        }
        
        public System.Threading.Tasks.Task<string> CallServiceAsync(string sInputMessage) {
            return base.Channel.CallServiceAsync(sInputMessage);
        }
        
        public ImrPlatform.JirehService.CompositeType GetDataUsingDataContract(ImrPlatform.JirehService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ImrPlatform.JirehService.CompositeType> GetDataUsingDataContractAsync(ImrPlatform.JirehService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string FileDownload(string sDownloadUri, string sPort, string sUserID, string sUserPassword, string sFilename) {
            return base.Channel.FileDownload(sDownloadUri, sPort, sUserID, sUserPassword, sFilename);
        }
        
        public System.Threading.Tasks.Task<string> FileDownloadAsync(string sDownloadUri, string sPort, string sUserID, string sUserPassword, string sFilename) {
            return base.Channel.FileDownloadAsync(sDownloadUri, sPort, sUserID, sUserPassword, sFilename);
        }
        
        public string HttpDownload(string FileKind, string FilePath) {
            return base.Channel.HttpDownload(FileKind, FilePath);
        }
        
        public System.Threading.Tasks.Task<string> HttpDownloadAsync(string FileKind, string FilePath) {
            return base.Channel.HttpDownloadAsync(FileKind, FilePath);
        }
    }
}
