//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImrPlatform.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImrPlatform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CAAM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_ANIMAL {
            get {
                return ResourceManager.GetString("CAT_ANIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_EDUCATION {
            get {
                return ResourceManager.GetString("CAT_EDUCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAGA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_GAME {
            get {
                return ResourceManager.GetString("CAT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_NATURE {
            get {
                return ResourceManager.GetString("CAT_NATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CASA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_SAFE {
            get {
                return ResourceManager.GetString("CAT_SAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CASC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_SCIENCE {
            get {
                return ResourceManager.GetString("CAT_SCIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CASF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAT_SF {
            get {
                return ResourceManager.GetString("CAT_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   별점과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CONTENT_STAR_RATE_TITLE {
            get {
                return ResourceManager.GetString("CONTENT_STAR_RATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홍수현과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DEMO_CONTENT_COPYWRITER {
            get {
                return ResourceManager.GetString("DEMO_CONTENT_COPYWRITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부엉이들의 삶과 죽음, 생태계에 미치는 영향을 VR 동영상으로 만든 컨텐츠입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DEMO_CONTENT_DESC {
            get {
                return ResourceManager.GetString("DEMO_CONTENT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   14K과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DEMO_CONTENT_DOWNRATE {
            get {
                return ResourceManager.GetString("DEMO_CONTENT_DOWNRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100,000과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DEMO_CONTENT_PRICE {
            get {
                return ResourceManager.GetString("DEMO_CONTENT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ★★★★★과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DEMO_CONTENT_RATE {
            get {
                return ResourceManager.GetString("DEMO_CONTENT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부엉이 생태계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DEMO_CONTENT_TITLE {
            get {
                return ResourceManager.GetString("DEMO_CONTENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap icon_sidepopup_pick {
            get {
                object obj = ResourceManager.GetObject("icon_sidepopup_pick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap icon_sidepopup_purchase {
            get {
                object obj = ResourceManager.GetObject("icon_sidepopup_purchase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap icon_sidepopup_review {
            get {
                object obj = ResourceManager.GetObject("icon_sidepopup_review", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOGIN_ID_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_ID_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOGIN_PW_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_PW_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOGIN_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOGOUT_TEXT {
            get {
                return ResourceManager.GetString("LOGOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MONETARY_UNIT {
            get {
                return ResourceManager.GetString("MONETARY_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찜목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MY_LIST_TITLE {
            get {
                return ResourceManager.GetString("MY_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구매내역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PURCHASE_HISTORY_TITLE {
            get {
                return ResourceManager.GetString("PURCHASE_HISTORY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리뷰내역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REVIEW_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVIEW_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저작권과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_COPY_WRITE {
            get {
                return ResourceManager.GetString("STRING_COPY_WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리뷰과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string USER_REVIEW {
            get {
                return ResourceManager.GetString("USER_REVIEW", resourceCulture);
            }
        }
    }
}
